name: Run blocks

on:
  workflow_dispatch:

jobs:
  # Block 1: Confluence_Input
  Confluence_Input:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
        echo "Read Inputs from Confluence"

  # Block 2: Test (depends on Confluence_Input)
  ARXML_difference:
    runs-on: ubuntu-latest
    needs: Confluence_Input
    steps:
      - name: Checkout code
        run: |
        echo "Find ARXML Difference"

  # Block 3: Deploy (depends on test)
  Config_check:
    runs-on: ubuntu-latest
    needs: ARXML_difference
    steps:
      - name: Checkout code
        run: |
        echo "Config check"
  # Block 3: Deploy (depends on test)
  Integration_check:
    runs-on: ubuntu-latest
    needs: Config_check
    steps:
      - name: Checkout code
        run: |
        echo "Integration_check"
  # Block 3: Deploy (depends on test)
  Apply_cahnges_To_Feature_Branch:
    runs-on: ubuntu-latest
    needs: Integration_check
    steps:
      - name: Checkout code
        run: |
        echo "Apply_cahnges_To_Feature_Branch"
  # Block 3: Deploy (depends on test)
  verify_Diff_Application:
    runs-on: ubuntu-latest
    needs: Apply_cahnges_To_Feature_Branch
    steps:
      - name: Checkout code
        run: |
        echo "verify_Diff_Application"
